CREATE TABLE [dbo].[dim_date](
	[date_key] [int] IDENTITY(1,1) NOT NULL,
	[actual_date] [date] NULL,
	[iso_date] [char](8) NULL,
	[is_weekday] [bit] NULL,
	[is_weekend] [bit] NULL,
	[day_short_name] [char](3) NULL,
	[day_long_name] [varchar](9) NULL,
	[day_of_week] [tinyint] NULL,
	[day_of_month] [tinyint] NULL,
	[day_of_year] [smallint] NULL,
	[week_of_year_key] [int] NULL,
	[week_of_year] [tinyint] NULL,
	[week_of_year_name] [char](7) NULL,
	[week_of_month] [tinyint] NULL,
	[week_start_date_monday] [date] NULL,
	[week_end_date_sunday] [date] NULL,
	[week_start_date_saturday] [date] NULL,
	[week_end_date_friday] [date] NULL,
	[week_start_name_monday] [char](11) NULL,
	[week_end_name_sunday] [char](11) NULL,
	[week_start_name_saturday] [char](11) NULL,
	[week_end_name_friday] [char](11) NULL,
	[month_key] [int] NULL,
	[month_of_year] [tinyint] NULL,
	[month_long_name] [varchar](9) NULL,
	[month_short_name] [char](3) NULL,
	[month_full_name] [varchar](8) NULL,
	[month_remaining_days] [tinyint] NULL,
	[last_day_of_month] [date] NULL,
	[calendar_quarter_key] [int] NULL,
	[calendar_quarter_long_name] [char](9) NULL,
	[calendar_quarter_short_name] [char](5) NULL,
	[calendar_month] [int] NULL,
	[financial_quarter_key] [int] NULL,
	[financial_quarter_name] [char](10) NULL,
	[calendar_year_key] [int] NULL,
	[calendar_year_name] [char](4) NULL,
	[calendar_year_start] [date] NULL,
	[calendar_year_end] [date] NULL,
	[calendar_year_remaining_days] [smallint] NULL,
	[financial_year_key] [int] NULL,
	[financial_year_name] [char](7) NULL,
	[financial_year_start] [date] NULL,
	[financial_year_end] [date] NULL,
	[financial_year_remaining_days] [smallint] NULL,
	[financial_year_quarter] [char](2) NULL,
	[financial_month] [int] NULL,
	[is_last_day_of_month] [bit] NULL,
	[is_last_day_of_calendar_year] [bit] NULL,
	[is_last_day_of_financial_year] [bit] NULL,
 CONSTRAINT [PK_Date] PRIMARY KEY CLUSTERED 
(
	[date_key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO