CREATE TABLE [lead].[dim_status]
(
	[status_key] [int] IDENTITY(1,1) NOT NULL,
    [status] VARCHAR(250) NULL, 
    [message] VARCHAR(500) NULL,
 CONSTRAINT [PK_status] PRIMARY KEY CLUSTERED 
(
	[status_key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
