CREATE TABLE [lead].[dim_affiliate]
(
	[affiliate_key] [int] IDENTITY(1,1) NOT NULL,
    [affiliate_id] VARCHAR(250) NULL,
CONSTRAINT [PK_affiliate] PRIMARY KEY CLUSTERED 
(
	[affiliate_key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

