CREATE TABLE [lead].[dim_source]
(
	[source_key] [int] IDENTITY(1,1) NOT NULL,
    [source] VARCHAR(250) NULL
 CONSTRAINT [PK_source] PRIMARY KEY CLUSTERED 
(
	[source_key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
